### ISSUE TITLE
Why is the API so poor? It doesn't have API requests like getting holds, logging in, etc.

### ISSUE THREAD

**Issue by developerfromjokela** [NatLibFi/NDL-VuFind2#1559]
Hello,

I'm writing an mobile app for Kirkes. I'm little disappointed to see that the API lacks requests like login, holds, etc. Are there any plans to do them?

Looking forward to your answer. :smile: 

@developerfromjokela

**Comment by EreMaijala** [comment]
Hi,

We have prioritized functionality that's provided by Finna directly (that is, not with Finna acting as sort of a proxy for another system). The functionality for library card login, holds, renewals etc. is provided by the various library management systems (LMS) via their own APIs. That means it's already possible (at least in theory) to use those APIs to build additional functionaly. It's not an easy task to create consistent APIs on top of APIs of different LMS since the functionality that each system provides differs in subtle and not so subtle ways. One additional consideration is that we can provide access to Finna's current APIs with no concern on the effect they might have on the LMS.

All that said, we understand the need and desire to have a single entrypoint to all the services. The matter is just way more complex than just providing a proxy API.

**Comment by EreMaijala** [comment]
Issue noted for further development.

**Comment by developerfromjokela** [comment]
Can I access the 'other API or as you mentioned 'LMS''? I can make my own API if your developers are focused on other things that are more important than this API.

**Comment by EreMaijala** [comment]
Please contact the library in question. It's up to them to decide whether to provide access to their API.

**Comment by developerfromjokela** [comment]
@EreMaijala Do you know and are you able to tell me which IMS/LMS are Kirkes libraries using?

**Comment by developerfromjokela** [comment]
> Hi,
> 
> We have prioritized functionality that's provided by Finna directly (that is, not with Finna acting as sort of a proxy for another system). The functionality for library card login, holds, renewals etc. is provided by the various library management systems (LMS) via their own APIs. That means it's already possible (at least in theory) to use those APIs to build additional functionaly. It's not an easy task to create consistent APIs on top of APIs of different LMS since the functionality that each system provides differs in subtle and not so subtle ways. One additional consideration is that we can provide access to Finna's current APIs with no concern on the effect they might have on the LMS.
> 
> All that said, we understand the need and desire to have a single entrypoint to all the services. The matter is just way more complex than just providing a proxy API.

You said that you have different LMSes and different APIs and it's hard to make into one API. How does the Finna work then? finna.fi has a lots of authentication methods from various LMSes.

**Comment by EreMaijala** [comment]
@developerfromjokela Kirkes is using Axiell Aurora.

For Finna, a lot of work has gone to making things appear as consistent as possible. However, there are a lot of minor and major differences between the systems, and while we can work around many of them, providing all the functionality in a consistent API is a huge task. 

I'll give a quick example from one of the most complicated tasks, placing a hold request: take two libraries, A and B, and there could be the following differences:
- A needs you to just select a pickup location. B needs you to select a logical group of libraries first, and only then you can select a pickup location belonging to the selected group.
- A needs you to tick a box making sure you're aware of the open pickup stacks. B needs you to visit the service desk.
- A allows you to place hold on items on shelf. B doesn't.
- B allows you to place hold on a single item instead of any item of the bibliographic record. A doesn't.
- B allows you to enter a note alongside the request. A doesn't.
- A wants to display an introduction text with link to terms of use in the hold screen. B doesn't.
- A allows you to freeze a hold so that it doesn't become available for pickup. B doesn't.

The list goes on. I need to stress that it's not impossible to provide all this via an API, but it's quite possible that the API won't be as easy to use as one would like.

**Comment by developerfromjokela** [comment]
Ok. I understand.

Are you aware what LMS does Kirkes use?

**Comment by EreMaijala** [comment]
> @developerfromjokela Kirkes is using Axiell Aurora.

**Comment by developerfromjokela** [comment]
Ok. Thank you. I'll contact them to request their API.

**Comment by developerfromjokela** [comment]
Sad, but they rejected to give me access to their API.
