### ISSUE TITLE
Advanced Search's complex queries fail when search terms are combined with a geographic filter

### ISSUE THREAD

**Issue by ttoljamo** [NatLibFi/NDL-VuFind2#2023]
Advanced Search's complex queries fail when search terms are combined with a geographic filter. 

Steps to reproduce: 
- Use advanced search
- Add a common search term 
- Add a large region filter 
- Execute the query

Result: 0 hits.

If those same search terms and geographic filters were applied using the search box and side-facets, the results would be different. 

The issue seems to be at module/Finna/src/Finna/Search/Solr/SolrExtensionsListener.php: 
```
// Set also default query type since bq only works with
// DisMax and eDisMax.
$params->set('defType', 'edismax');
```

When setting the 'edismax' is commented out, the error cannot be reproduced anymore -- but does it break something else?

Cheers,
Tuomo

**Comment by EreMaijala** [comment]
@ttoljamo Thanks for bringing this up. That's indeed bad, and could be result of some subtle change in Solr since I'm pretty sure it has worked before. Your suggestion on removing the defType parameter makes sense in any case, since the boost should not try to dictate the query parser used. eDisMax is always used anyway if possible, and if not, it's typically a case where the boost wouldn't make a meaningful difference. I think it might make sense to also switch to `boost` instead of `bq` for multiplicative boost instead of additive, but that's something to evaluate another time.

**Comment by EreMaijala** [comment]
Fix pushed to production.
