### ISSUE TITLE
mobile instead of phone in updatePhone function KohaRest.php

### ISSUE THREAD

**Issue by JacobSandin** [NatLibFi/NDL-VuFind2#2348]
Hi, 

I think there might be an error in updatePhone if it is not intentional.

`    public function updatePhone($patron, $phone)
    {
        return $this->updatePatron($patron, ['mobile' => $phone]);
    }
`
it say mobile, but I think should be "phone"

**Comment by EreMaijala** [comment]
@JacobSandin Sorry to have kept this lingering. I finally took the moment to check this out. This is not really a bug but a a design decision. Long ago it was decided that mobile phone number would be the main one in Finnish Koha libraries, and this just reflects the decision. However, the feature has been deprecated because of the confusion caused by multiple ways that the different pieces of user information were updated. We nowadays use mostly the "updateAddress" functionality (which is a bit of a misnomer, I know) for all the updates.
