### ISSUE TITLE
What the fuck?

### ISSUE THREAD

**Issue by developerfromjokela** [NatLibFi/NDL-VuFind2#2411]
Google has been notified that aspects of your application, OpenFinna, allegedly infringe upon the trademarks of others.

You may contact University of Helsinki/National Library of Finland at [email redacted].

🤨🤨

Don't you all have anything better to do  @ NatLibFi? For example make this shithole work as intended. If you can't care any less about your shit, at least don't interfere with others trying to make it better for others.

**Comment by EreMaijala** [comment]
It is our duty to defend our trademark. Since there was a real chance of OpenFinna (or "Open Finna" as it was also written) to be wrongly associated with Finna, we had to take action. We also have to take action if we find an application to infringe the terms governing the use of our service.

We care about our stuff and we welcome issue reports, enhancement requests as well as pull requests to improve the functionality of Finna. There are, however, several technical and non-technical reasons why we cannot promise to fulfil all the requests.

We also encourage contributing directly to VuFind (https://github.com/vufind-org/vufind), which Finna is based on, when the functionality could be deemed useful for the international audience.

**Comment by developerfromjokela** [comment]
bullshit
